version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version

  build:
    commands:
      - echo Building project inside cms folder...
      - cd cms
      - mvn clean package -DskipTests

artifacts:
  files:
    - cms/target/cms.war
  discard-paths: yes
